// SPDX-License-Identifier: NOASSERTION
#include "Dxf/UiDefaultStyles.h"
#include "Dxf/UiStyleParser.h"
namespace Dxf
{
// 組込みの既定スタイルの資源。
const char* GetBuiltInUiStyleText() noexcept
{
	return "dxfui-style 1\n"
	       "# 組込みの既定スタイル（ライブラリに含める。外部の資源で同じIDを定義すると、そちらを使う）。\n"
	       "token color.text = #EBEBF0\n"
	       "token color.text.dim = #9A9AA8\n"
	       "token color.surface = #1C1C24F0\n"
	       "token color.surface.raised = #2A2A36\n"
	       "token color.surface.hover = #36364A\n"
	       "token color.surface.pressed = #22222E\n"
	       "token color.accent = #3A7BFF\n"
	       "token color.accent.hover = #5A95FF\n"
	       "token color.focus = #FFD24A\n"
	       "token color.border = #4A4A5E\n"
	       "token color.backdrop = #00000099\n"
	       "token color.disabled = #6A6A78\n"
	       "token size.text = 20\n"
	       "token size.text.small = 16\n"
	       "token size.text.title = 36\n"
	       "token size.gap = 8\n"
	       "token size.border = 1\n"
	       "token size.focus = 2\n"
	       "default {\n"
	       "    foreground = @color.text\n"
	       "    font-size = @size.text\n"
	       "    font-family = \"Meiryo\"\n"
	       "}\n"
	       "style Panel {\n"
	       "    background = @color.surface\n"
	       "    border-color = @color.border\n"
	       "    border-width = @size.border\n"
	       "    padding = 12\n"
	       "}\n"
	       "style Label {\n"
	       "    foreground = @color.text\n"
	       "    font-size = @size.text\n"
	       "}\n"
	       "style Label.Title {\n"
	       "    foreground = @color.text\n"
	       "    font-size = @size.text.title\n"
	       "}\n"
	       "style Label.Dim {\n"
	       "    foreground = @color.text.dim\n"
	       "    font-size = @size.text.small\n"
	       "}\n"
	       "style Button {\n"
	       "    background = @color.surface.raised\n"
	       "    foreground = @color.text\n"
	       "    border-color = @color.border\n"
	       "    border-width = @size.border\n"
	       "    padding = 16 8\n"
	       "    hover.background = @color.surface.hover\n"
	       "    pressed.background = @color.surface.pressed\n"
	       "    focus.border-color = @color.focus\n"
	       "    focus.border-width = @size.focus\n"
	       "    disabled.foreground = @color.disabled\n"
	       "    disabled.background = @color.surface\n"
	       "}\n"
	       "style Button.Primary {\n"
	       "    background = @color.accent\n"
	       "    foreground = #FFFFFF\n"
	       "    padding = 16 8\n"
	       "    hover.background = @color.accent.hover\n"
	       "    pressed.background = @color.surface.pressed\n"
	       "    focus.border-color = @color.focus\n"
	       "    focus.border-width = @size.focus\n"
	       "    disabled.background = @color.surface\n"
	       "    disabled.foreground = @color.disabled\n"
	       "}\n"
	       "style Toggle {\n"
	       "    foreground = @color.text\n"
	       "    padding = 4\n"
	       "    hover.background = @color.surface.hover\n"
	       "    focus.border-color = @color.focus\n"
	       "    focus.border-width = @size.focus\n"
	       "    disabled.foreground = @color.disabled\n"
	       "}\n"
	       "style Toggle.Box {\n"
	       "    background = @color.surface.raised\n"
	       "    border-color = @color.border\n"
	       "    border-width = @size.border\n"
	       "}\n"
	       "style Toggle.Check {\n"
	       "    background = @color.accent\n"
	       "}\n"
	       "style Slider {\n"
	       "    background = @color.surface.raised\n"
	       "    foreground = @color.accent\n"
	       "    border-color = @color.border\n"
	       "    border-width = @size.border\n"
	       "    focus.border-color = @color.focus\n"
	       "    focus.border-width = @size.focus\n"
	       "    disabled.foreground = @color.disabled\n"
	       "}\n"
	       "style Slider.Thumb {\n"
	       "    background = @color.text\n"
	       "    hover.background = #FFFFFF\n"
	       "    pressed.background = @color.accent.hover\n"
	       "}\n"
	       "style ProgressBar {\n"
	       "    background = @color.surface.raised\n"
	       "    foreground = @color.accent\n"
	       "    border-color = @color.border\n"
	       "    border-width = @size.border\n"
	       "}\n"
	       "style ScrollView {\n"
	       "    background = #00000000\n"
	       "}\n"
	       "style ScrollBar {\n"
	       "    background = #FFFFFF18\n"
	       "}\n"
	       "style ScrollBar.Thumb {\n"
	       "    background = #FFFFFF50\n"
	       "    hover.background = #FFFFFF80\n"
	       "    pressed.background = @color.accent\n"
	       "}\n"
	       "style ListRow {\n"
	       "    padding = 8 4\n"
	       "    hover.background = @color.surface.hover\n"
	       "    focus.border-color = @color.focus\n"
	       "    focus.border-width = @size.focus\n"
	       "}\n"
	       "style ListRow.Selected {\n"
	       "    background = @color.accent\n"
	       "    foreground = #FFFFFF\n"
	       "    padding = 8 4\n"
	       "    focus.border-color = @color.focus\n"
	       "    focus.border-width = @size.focus\n"
	       "}\n"
	       "style Popup.Backdrop {\n"
	       "    background = @color.backdrop\n"
	       "}\n"
	       "style Popup {\n"
	       "    background = @color.surface\n"
	       "    border-color = @color.accent\n"
	       "    border-width = 2\n"
	       "    padding = 16\n"
	       "}\n"
	       "style Tooltip {\n"
	       "    background = #101018F0\n"
	       "    foreground = @color.text\n"
	       "    border-color = @color.border\n"
	       "    border-width = 1\n"
	       "    font-size = @size.text.small\n"
	       "    padding = 8 4\n"
	       "}\n"
	       "style Image {\n"
	       "}\n";
}
// 組込みの既定スタイル。
Toolbox::TSharedPtr<const FUiStyleSheet> GetBuiltInUiStyleSheet()
{
	// 初回だけ読み、以後は共有する（読込の失敗はライブラリの誤りなので例外）。
	static const Toolbox::TSharedPtr<const FUiStyleSheet> Sheet = []
	{
		auto Parsed = ParseUiStyleSheet("BuiltIn.dxfui", GetBuiltInUiStyleText());
		if (!Parsed)
		{
			throw Toolbox::FException(Parsed.Error().Message.CStr());
		}
		return Toolbox::TSharedPtr<const FUiStyleSheet>(
		    Toolbox::MakeShared<FUiStyleSheet>(Toolbox::Move(Parsed).Value()));
	}();
	return Sheet;
}
} // namespace Dxf
